name: Reset Production

on:
  # Run at 2AM every night
  schedule:
    - cron: '0 10 * * *'

  # Also support manual
  workflow_dispatch:

jobs:

  reset:
    name: Reset Production
    runs-on: ubuntu-latest
    steps:

      - name: Install
        uses: bkwld/cloak-actions/install@v1

      - name: Reset Dataset
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.RESET_DATASET_SANITY_API_TOKEN }}
        run:
          npx -y sanity@latest
          dataset import backups/production.gz production --replace
